name: Minify

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            - name: Git checkout
              uses: actions/checkout@v3

            - name: Minify Action
              uses: anthonyftwang/minify-action@v1.0.1
